### ISSUE TITLE
license migration to SPDX

### ISSUE THREAD

**Issue by martinkg** [thothix/guayadeque#11]
Hi,

I have released the new version of [guayadeque-0.6.0](https://src.fedoraproject.org/rpms/guayadeque/blob/rawhide/f/guayadeque.spec) for Fedora and migrated the license to SPDX.
However, I am not sure if this is correct.

The file [guayadeque.appdata.xml](https://github.com/thothix/guayadeque/blob/master/defconfig/guayadeque.appdata.xml) still contains the following license information `<project_license>GPL-3.0+ and BSD and LGPL-2.0+ and wxWidgets</project_license>`

I have asked about this in the [Fedora developer forum](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/WP4IJA5JY4E4H2L67VUY2PMGQEUSALLQ/)   , but have not received a definitive answer. I should clarify this upstream.

Can you help to clarify the license problem ?

**Comment by thothix** [comment]
Hi,
Guayadeque doesn't use wxWidgets and LGPL-2+ licenses anymore.
wxWidgets license was used by src/wx/Curl/* that was removed from the source and the LGPL-2+ I don't know where it was used, I didn't find any reference to it.
I'm working to update the debian package right now and I did some metadata updates, so the appdata.xml now contains   <project_license>GPL-3.0+ and BSD-3-Clause</project_license>. I intend to release this changes in v0.6.1. 

The 0.6.1 will contain only files/metadata changes. The "guayadeque.appdata.xml" was renamed to "org.guayadeque.guayadeque.metainfo.xml" and will be placed in metainfo/ directory instead of appdata/ and "guayadeque.desktop" was renamed to "org.guayadeque.guayadeque.desktop"

**Comment by thothix** [comment]
Ok, I found an error in recent header files. The src/taginfo/TagInfo.* mentioned LGPL. I'm going to fix that and only the wxWidgets license will be removed.

**Comment by thothix** [comment]
I found an error in the recent header files for "src/taginfo/TagInfo.*". It was LGPL but the former header has errors as well.

//    Copyright (C) 2008-2023 J.Rios anonbeat@gmail.com
//
//    This library is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Lesser General Public
//    License as published by the Free Software Foundation; either
//    version 2.1 of the License, or (at your option) any later version.
//
//    This Program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; see the file LICENSE.  If not, write to
//    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
//    Boston, MA 02110-1301 USA.
//
//    http://www.gnu.org/copyleft/gpl.html

This text is wrong. It mentions "GNU Lesser General Public License" in the beginning but mentions "GNU General Public License" 2 times after that. 
The TagLib library is LGPL, I don't know if the code that use it needs to be LGPL or if it can be GPL3...

**Comment by thothix** [comment]
Ok, I checked it out and I can license the code that uses a LGPL-2 library (TagLib in this case) as GPL-3+.
So I'll maintain the current header (GPL-3+) for TagInfo.* files and remove the LGPL-2 from appdata.xml.

**Comment by thothix** [comment]
There's some changes in the config files for v0.6.1 so you'll need to do some adjustments in your .spec file.

The changes are related to this:

install(FILES defconfig/guayadeque.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/64x64/apps/)
install(FILES defconfig/org.guayadeque.guayadeque.desktop DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/applications)
install(FILES defconfig/org.guayadeque.guayadeque.metainfo.xml DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/metainfo)

Now they have different names and/or target locations.

The changes are already in the guayadeque/dev branch.

**Comment by thothix** [comment]
https://github.com/thothix/guayadeque/issues/10#issuecomment-2469005987

**Comment by martinkg** [comment]
Thank you for clarifying the license issue. Until when can I expect the release of 0.6.1, as there is no 0.6.1 tag yet.

**Comment by martinkg** [comment]
can you please use the SPDX-License-Identifier: GPL-3.0-or-later AND BSD-3-Clause
in the file defconfig/org.guayadeque.guayadeque.metainfo.xml

**Comment by thothix** [comment]
> can you please use the SPDX-License-Identifier: GPL-3.0-or-later AND BSD-3-Clause in the file defconfig/org.guayadeque.guayadeque.metainfo.xml

Sure, I'm going to update it.

I'm going to release it this evening. I'm at UTC-3 here.

**Comment by martinkg** [comment]
Great Thanks

**Comment by thothix** [comment]
v0.6.1 released!

**Comment by thothix** [comment]
v0.6.1 released!

**Comment by thothix** [comment]
I reissued the release right now! If you already used it, please update the release commit.

**Comment by martinkg** [comment]
guayadeque-0.6.1 was released for Fedora F40, F41 and F42
