### ISSUE TITLE
missing menu text in german

### ISSUE THREAD

**Issue by martinkg** [thothix/guayadeque#14]
Hi,

I am missing the translation of this menu text to german

msgid "Enable equalizer"
msgstr "Equalizer aktivieren"

and

msgid "Enable volume and fader"
msgstr "Lautstärke und Fader aktivieren"

and correction of this typo

msgid "Show notifications"
msgstr "Benachrichtigungen einbelenden"
to
msgid "Show notifications"
msgstr "Benachrichtigungen einblenden"

Thanks
Martin

**Comment by filochard** [comment]
Hi
Martin
May you have a look to https://github.com/thothix/guayadeque/issues/10#issuecomment-2469477038
I have proposed to add some translations (French Italian and Greek) to the desktop file
Would you please add some german translations too
Thanks

Besides this https://github.com/thothix/guayadeque/issues/13#issuecomment-2472248784
Tiago is asking for translations in French but I think it would be useful to propose German translations too

Thanks

**Comment by martinkg** [comment]
should also be corrected

```
#: ui/preferences/Preferences.cpp:541
msgid "Show album cover in the player"
msgstr "Albumcover im Player anzeigen"


#: ui/preferences/Preferences.cpp:545
msgid "Show CD cover frame in the cover editor"
msgstr "CD-Cover-Rahmen im Cover-Editor anzeigen"
```

**Comment by thothix** [comment]
The translations are already in dev branch (0.6.2-beta).

**Comment by martinkg** [comment]
I have found 3 more texts that have not yet been translated.

```
#: ui/preferences/Preferences.cpp:1483
msgid "Proxy Enabled"
msgstr "Proxy Aktiviert"

#: ui/preferences/Preferences.cpp:1395
msgid " Disabled Genres "
msgstr " Deaktivierte Genres "

#: ui/preferences/Preferences.cpp:3363
msgid "Enter the genre to disable"
msgstr "Geben Sie das zu deaktivierende Genre ein"
```

**Comment by martinkg** [comment]
have once again discovered and translated forgotten menu text.

```
#: ui/player/PlayerPanel.cpp:170
msgid "Stops the current track"
msgstr "Stoppt den aktuellen Titel"

#: ui/player/PlayerPanel.cpp:2561
msgid "Smart mode enabled"
msgstr "Smart-Modus aktiviert"

#: ui/player/PlayerPanel.cpp:197
msgid "Show the equalizer (right click for on/off)"
msgstr "Equalizer anzeigen (Rechtsklick für Ein/Aus)"

#: ui/player/PlayList.cpp:68
msgid "Move the selected tracks to the top"
msgstr "Verschiebe die ausgewählten Titel an den Anfang"

#: ui/player/PlayList.cpp:72
msgid "Move the selected tracks up"
msgstr "Verschiebe die ausgewählten Titel nach oben"

#: ui/player/PlayList.cpp:76
msgid "Move the selected tracks down"
msgstr "Verschiebe die ausgewählten Titel nach unten"

#: ui/player/PlayList.cpp:80
msgid "Move the selected tracks to the bottom"
msgstr "Verschiebe die ausgewählten Titel ans Ende der Liste"
```

**Comment by martinkg** [comment]
[guayadeque.po.txt](https://github.com/user-attachments/files/17796700/guayadeque.po.txt)

**Comment by martinkg** [comment]
[guayadeque.po.txt](https://github.com/user-attachments/files/17796711/guayadeque.po.txt)

**Comment by martinkg** [comment]
I have completely translated the German menu text again.
I have used guayadeque/po/guayadeque.pot as a reference.
Attached is the de/guayadeque.po
[guayadeque.po.txt](https://github.com/user-attachments/files/17802808/guayadeque.po.txt)

**Comment by filochard** [comment]
Hi Martin
please note that inside guayadeque/po/guayadeque.pot these lines don't exist yet in the end of the file (and have now no reference to any .ccp source file) :

msgid "Browse in File Manager"
msgstr ""

msgid "Burn as AudioCD using Brasero"
msgstr ""

msgid "Burn as DataCD using Brasero"
msgstr ""

msgid "Open Terminal in directory"
msgstr ""

msgid "Edit cover using GIMP"
msgstr ""

msgid "To mp3"
msgstr ""

@thothix 
May you add this in the .pot file for coherency with other translations

**Comment by thothix** [comment]
> Hi Martin please note that inside guayadeque/po/guayadeque.pot these lines don't exist yet in the end of the file (and have now no reference to any .ccp source file) :
> 
> msgid "Browse in File Manager" msgstr ""
> 
> msgid "Burn as AudioCD using Brasero" msgstr ""
> 
> msgid "Burn as DataCD using Brasero" msgstr ""
> 
> msgid "Open Terminal in directory" msgstr ""
> 
> msgid "Edit cover using GIMP" msgstr ""
> 
> msgid "To mp3" msgstr ""
> 
> @thothix May you add this in the .pot file for coherency with other translations

@filochard,  I cannot add this to .pot file because it is automatically generated by compilation. If I add them, they will be lost at build.

This messages aren't added in the .pot file because they are not referenced in any source file (as you stated), they are external text messages from .conf file.

I don't know if there's any standard way to handle this. I'm going to look further on this. By now we need to add them by hand in .po files

**Comment by thothix** [comment]
> I have completely translated the German menu text again. I have used guayadeque/po/guayadeque.pot as a reference. Attached is the de/guayadeque.po [guayadeque.po.txt](https://github.com/user-attachments/files/17802808/guayadeque.po.txt)

I have no way to compare your guayadeque.po.txt file, it looks very different from the current .po

**Comment by thothix** [comment]
> > I have completely translated the German menu text again. I have used guayadeque/po/guayadeque.pot as a reference. Attached is the de/guayadeque.po [guayadeque.po.txt](https://github.com/user-attachments/files/17802808/guayadeque.po.txt)
> 
> I have no way to compare your guayadeque.po.txt file, it looks very different from the current .po

Ok, I ordered the file with poedit and I'm updating it.

**Comment by thothix** [comment]
@martinkg, there's some translations I found incomplete or wrong.
You can search for ' msgstr "" ' in the .po file to find them.
I have already commited the last updates to dev.

**Comment by martinkg** [comment]
@thothix
I have revised the guayadeque.po again and attached it.
[guayadeque.po.txt](https://github.com/user-attachments/files/17827901/guayadeque.po.txt)

**Comment by thothix** [comment]
> @thothix I have revised the guayadeque.po again and attached it. [guayadeque.po.txt](https://github.com/user-attachments/files/17827901/guayadeque.po.txt)

Commited to dev branch

**Comment by martinkg** [comment]
sorry, but the translation of the following 4 menu texts into German is still missing in the dev branch.
```
#: ui/player/PlayList.cpp:68
msgid "Move the selected tracks to the top"
msgstr "Verschiebe die ausgewählten Titel an den Anfang"

#: ui/player/PlayList.cpp:72
msgid "Move the selected tracks up"
msgstr "Verschiebe die ausgewählten Titel nach oben"

#: ui/player/PlayList.cpp:76
msgid "Move the selected tracks down"
msgstr "Verschiebe die ausgewählten Titel nach unten"

#: ui/player/PlayList.cpp:80
msgid "Move the selected tracks to the bottom"
msgstr "Verschiebe die ausgewählten Titel ans Ende der Liste"
```
is there a possibility to customize the menu texts of guayadeque via transifex, that would make things a lot easier.
