### ISSUE TITLE
Here is a totally rewritten french po file

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#16]
I have totally rewritten the french guayadeque.po file so that it is totally coherent with guayadeque.pot file from today : 
24-11-19 16:24-300   
;o)
I have renamed it fr-guayadeque.po.txt so that there is no confusion with other po files and with a txt suffix so that it can be uploaded here 

I don't know if it is possible for you to simply replace the actual french po file by this one  : this would make it easier to update in the future

**Comment by filochard** [comment]
sync with pot 24-11-19 19:53-300
[fr-guayadeque.po.txt](https://github.com/user-attachments/files/17822946/fr-guayadeque.po.txt)

**Comment by filochard** [comment]
sync with pot 24-11-19 19:53-300 with & in the right position in the translation
[fr-guayadeque.po.txt](https://github.com/user-attachments/files/17823019/fr-guayadeque.po.txt)

**Comment by filochard** [comment]
Here it is at lest : sync with pot 24-11-19 19:53-300 with the & in the right positions  for the translations
I have verified with poedit that the translations respected spaces and punctuation 
I really hope that it is possible for you to replace the french po file inside github with this one that is totally synchronized with your last pot file

[fr-guayadeque.po.txt](https://github.com/user-attachments/files/17823280/fr-guayadeque.po.txt)

**Comment by thothix** [comment]
Ok. I'm going to add the messages out of .pot that are in the end of the current .po file.

**Comment by thothix** [comment]
> Here it is at lest : sync with pot 24-11-19 19:53-300 with the & in the right positions for the translations I have verified with poedit that the translations respected spaces and punctuation I really hope that it is possible for you to replace the french po file inside github with this one that is totally synchronized with your last pot file
> 
> [fr-guayadeque.po.txt](https://github.com/user-attachments/files/17823280/fr-guayadeque.po.txt)


Commited to dev branch
