### ISSUE TITLE
a new issue to propose Translations

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#17]
Hi Tiago 
I suggest that we use this issue to propose some translations or to upload rewritten po files

here is the first

GREEK
============================
Here is the first for greek (it's called el-guayadeque.po.txt to prevent confusion and has been synchronized with the last pot file from today  ( 2024-11-20 14:22-0300)

**Comment by filochard** [comment]
and I have just discovered a little error :-(       
 I just omittted to add a & there
msgid "Force &Gapless Mode"
msgstr "Εξαναγκασμένη  αδιάλειπτη Λειτουργία"

should be
msgid "Force &Gapless Mode"
msgstr "Εξαναγκασμένη  αδιάλειπτη &Λειτουργία"

Poedit is pityless : it asks for missing spaces and strictly asks for capital letters or lowercase letters in the beginning of lines

I reupload it with these corrections    ;-)

**Comment by filochard** [comment]
[el-guayadeque.po.txt](https://github.com/user-attachments/files/17835050/el-guayadeque.po.txt)

I think it's the really good one

**Comment by thothix** [comment]
> and I have just discovered a little error :-( I just omittted to add a & there msgid "Force &Gapless Mode" msgstr "Εξαναγκασμένη αδιάλειπτη Λειτουργία"
> 
> should be msgid "Force &Gapless Mode" msgstr "Εξαναγκασμένη αδιάλειπτη &Λειτουργία"
> 
That's all right, I added it in the last commit!

> Poedit is pityless : it asks for missing spaces and strictly asks for capital letters or lowercase letters in the beginning of lines
> 

This leading and trailing spaces in the messages shouldn't exist! 
The correct should be add the spaces (formatting) in the source code. I already changed a couple ones but I think there's tens of messages like that. I'm going to update it (in all languages) little by little...

**Comment by thothix** [comment]
> This leading and trailing spaces in the messages shouldn't exist! The correct should be add the spaces (formatting) in the source code. I already changed a couple ones but I think there's tens of messages like that. I'm going to update it (in all languages) little by little...

These translations are always duplicated. Another example:

"Artist" and "Artist:"
They have duplicated translation for both but the ":" should be added by code (formatted)
And even we can have an additional " Artist ", that means 3 translations for the same word!

**Comment by filochard** [comment]
> 
> These translations are always duplicated. Another example:
> 
> "Artist" and "Artist:" They have duplicated translation for both but the ":" should be added by code (formatted) And even we can have an additional " Artist ", that means 3 translations for the same word!
 
I agree that " Artist " is a duplicate of "Artist"
But I think that "Artist:" as a reason to exits 
Same thing for all "xxx" and the useless " xxx "   but perhaps needed "xxx:"

**Comment by thothix** [comment]
> > These translations are always duplicated. Another example:
> > "Artist" and "Artist:" They have duplicated translation for both but the ":" should be added by code (formatted) And even we can have an additional " Artist ", that means 3 translations for the same word!
> 
> I agree that " Artist " is a duplicate of "Artist" But I think that "Artist:" as a reason to exits Same thing for all "xxx" and the useless " xxx " but perhaps needed "xxx:"

The reason for "Artist:" to exist is the same for " Artist ",  an extra character that has no meaning to the word.
And I'm removing them the same way.

I have a lot of duplicates removed, I'm commiting them right now before continue

**Comment by filochard** [comment]
OK

**Comment by thothix** [comment]
> 
> The reason for "Artist:" to exist is the same for " Artist ", an extra character that has no meaning to the word. And I'm removing them the same way.
> 
I think I wasn't clear, I'm removing them from the translation file not from the application. The translation code show the texts as it is now.

**Comment by filochard** [comment]
Hi Tiago 
Sorry for greek translations (el) : I have still found some typos, some errors, some inconsistency,  and worse of all some opposite  translations in greek about fade-in or fade-out  

#: misc/Accelerators.cpp:122
msgid "Gapless/Crossfading"
msgstr "Aδιάλειπτα/Με διασταυρούμενη εξασθένιση"
-------------------------instead of msgstr "Aδιάλειπτα/Με **αμφισοσταθμιστή έντασης**"

178 msgid "Repeat All Tracks"
179 msgstr "Επανάληψη Όλων των Κομματιών"   
------------------------------- instead of 179 msgtr "**Repeat All Tracks**"


1623 msgid ""
1624 "\n"
1625 "Continue deleting?"
1626 msgstr ""
1627 "\n"
1628 "Συνέχεια διαγραφής;"     
-------------------------------instead of 1628 "**Continue deleting?**"


1748 #: ui/taskbar/TaskBar.cpp:185 ui/MainFrame.cpp:1549
1749 msgid "Force &Gapless Mode"
1750 msgstr "Εξαναγκασμένη  &Αδιάλειπτη Λειτουργία" 
-----------------------------instead of 1750 msgtr "Εξαναγκασμένη  **&α**διάλειπτη Λειτουργία"


2857 #: ui/mediaviewer/albumbrowser/AlbumBrowser.cpp:435
2858 msgid "Sort albums by artist, year"
2859 msgstr "Ταξινόμηση των δίσκων κατά Καλλιτέχνη, Έτος"  
-----------------------------instead of 2859 msgstr "**Α**ξινόμηση των δίσκων κατά Καλλιτέχνη, Έτος"


3479 #: ui/lastfmpanel/LastFMPanel.cpp:1089 ui/lastfmpanel/LastFMPanel.cpp:1297
3480 msgid "Update the information with the current selected artist"
3481 msgstr "Ενημέρωση των πληροφοριών με τον επιλεγμένο καλλιτέχνη"  
---------------------instead of 3481 msgstr "Ενημέρωση των πληροφοριών με τον **επιλεγμένο του καλλιτέχνη**"
there is a **του** in surplus


3502 "%s\n"
3503 "%i plays by %u users"
3504 msgstr ""
3505 "%s\n"
3506 "%i ακροάσεις απο %u χρήστες"
------------------------ instead of  3506 "%i ακροάσεις απο %u χρήστες\""    
where there a too much \ and " in the end



4082 #: ui/preferences/Preferences.cpp:1050
4083 msgid "Select the length of the fade in"
4084 msgstr "Επιλογή του μήκους της σταδιακής αύξησης του ήχου (fade-in length)"
-------------------------instead of 4084 msgstr"Επιλογή του μήκους **της αποδυνάμωσης** (fade-in length)"


4086 #: ui/preferences/Preferences.cpp:1053
4087 msgid "Fade-in volume:"
4088 msgstr "Ένταση της σταδιακής αύξησης του ήχου (fade in):"
------------------------instead of  4088 msgstr "Ένταση της σταδιακής αύξησης του ήχου:"    
(fade in ) is missing at the end of the line



4090 #: ui/preferences/Preferences.cpp:1062
4091 msgid "Select the initial volume of the fade in"
4092 msgstr "Επιλογή της αρχικής έντασης ήχου της σταδιακής αύξησης του ήχου (fade-in)"
------------------------instead of 4092 msgstr "Επιλογή της αρχικής έντασης ήχου **της αποδυνάμωσης** (fade-in)"


4094 #: ui/preferences/Preferences.cpp:1065
4095 msgid "Fade-in start:"
4096 msgstr "Έναρξη της σταδιακής αύξησης του ήχου: (fade-in):"
-----------------------instead of 4096 msgstr "Έναρξη **αποδυνάμωσης** (fade-in):"


4644 #: ui/player/PlayerPanel.cpp:188 ui/player/PlayerPanel.cpp:3180
4645 msgid "Enable crossfading"
4646 msgstr "Ενεργοποίηση διασταυρούμενης εξασθένισης"
-------------------------instead of 4646 msgstr "Ενεργοποίηση **διασταυρωμένου ρυθμιστής**"


4648 #: ui/player/PlayerPanel.cpp:188 ui/player/PlayerPanel.cpp:3180
4649 msgid "Disable crossfading"
4650 msgstr "Απενεργοποίηση διασταυρούμενης εξασθένισης"
--------------------------instead of 4650 msgstr "Απενεργοποίηση **διασταυρωμένου ρυθμιστής**"


4732 #: ui/player/PlayList.cpp:85
4733 msgid "Randomize the tracks in playlist"
4734 msgstr "Τυχαία σειρά των κομματιών στη λίστα αναπαραγωγής"
--------------------------instead of 4734 msgstr "**Υχαία** σειρά των κομματιών στη λίστα αναπαραγωγής"

**Comment by thothix** [comment]
> Hi Tiago Sorry for greek translations (el) : I have still found some typos, some errors, some inconsistency, and worse of all some opposite translations in greek about fade-in or fade-out
> 
No problem. It's done!

I'm done with the translation refactoring as well.

**Comment by filochard** [comment]
Thanks

**Comment by filochard** [comment]
I have thought that it would be better to create pull requests for the French, the Italian and the Greek translations synchronized with the last pot file that I have written
Next translations would be easier...
