### ISSUE TITLE
A little detail

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#21]
Wrong release numbering in the page of the dev branch : maybe release might be 0.6.2 (except for the one automatically updated)

![wrong-release-numbers](https://github.com/user-attachments/assets/a0c343a8-bd97-4658-a071-fced61f467f5)

**Comment by thothix** [comment]
I didn't catch it. Where is the release numbering?
Those releases in the screen are from the commit messages when last updated.

**Comment by filochard** [comment]
Hi Tiago
Sorry for the noise
I wondered why for example :
- in front of build there is 0.5.2 release
- in front of Install.md  there is 0.6.0 release

**Comment by thothix** [comment]
> Hi Tiago Sorry for the noise I wondered why for example :
> 
>     * in front of build there is 0.5.2 release
> 
>     * in front of Install.md  there is 0.6.0 release

Ok, no problem.
Actually some of my commit messages are not the way it should be! I commited some changes in the commit to release a version. The only file that should have the release version for sure is the Changelog cause I update it with the release name and date when the release is done.
