### ISSUE TITLE
a little warning when launching from a console

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#23]
I usually never launch Guayadeque from the console but from the menu of my desktop

I tested launching it with the console and I have found this line repeated several times : 

(guayadeque:229147): Gtk-CRITICAL **: 12:22:07.141: gtk_widget_set_size_request: assertion 'height >= -1' failed

I don't know if this is specific to my distribution

NB that doesn't prevent Guayadeque to work normally

**Comment by thothix** [comment]
This messages are from wxWidgets and they are not critical as stated by the message.
A lot of projects have issues about this but they wasn't able to remove it.
They are only warnings indeed, so we need to live with this by now!

**Comment by filochard** [comment]
OK closing
