### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#25]
@martinkg
Hi Martin

You seem to know the use of poedit...

Some translations are still missing, some seem to be wrong for German...

I have synchronized guayadeque.po for german with the last guayadeque.pot file, and brought some cosmetic changes : deleting excess spaces and excess punctuations, adding missing spaces or punctuations, correcting some missing plurals (using plural existing for other msgstr)
There remain 
-some translations missing (empty line in the right column)
-some wrong translations (highlighted in yellow inside poedit)
-and maybe some errors that were not scanned by poedit

Would you be kind enough to review this .po file and correct it and then provide it here for Tiago (thothix) so that he may upload it to the code of the dev branch

(This has already been done for French, Italian, Greek and Spanish... adding German will make this improved version of Guayadeque more attractive for users  )

I will provide a more recently synchronized de-guayadeque.po file with the minor corrections, letting you complete it,
in the next comment

**Comment by thothix** [comment]
The plural form that we translated in Portuguese and French had no support from the .pot file and was lost.
Now I found out how to fix it but we need to put the plural translations back.

Please, can you fix for German ? 

(it's related to the last artists)

msgid "Don't repeat last"
msgid_plural "Don't repeat last"
msgstr[0] "singular"
msgstr[1] "plural"

**Comment by filochard** [comment]
Here is the latest synchronization with the .pot file
[de-guayadeque.po.txt](https://github.com/user-attachments/files/17968989/de-guayadeque.po.txt)

**Comment by thothix** [comment]
> Here is the latest synchronization with the .pot file [de-guayadeque.po.txt](https://github.com/user-attachments/files/17968989/de-guayadeque.po.txt)

This file seems to introduce some new errors.

I had not committed the updated German .po file before cause I was waiting to see if @martinkg would update it.
It's updated now like the others. And I pull some fixes from the above de-guayadeque.po.txt but not all of them.

You can see a lot of messages with "#|" like:

#| msgid "View the library genres"

This messages has the same translation as the message in the comment, so there's something wrong.

**Comment by thothix** [comment]
> Here is the latest synchronization with the .pot file [de-guayadeque.po.txt](https://github.com/user-attachments/files/17968989/de-guayadeque.po.txt)

Ok.

Only to remember: 

From now on, the .po files will be updated with the .pot file when the project is recompiled (build).
So new messages will be added (with blank translation), the removed ones will be commented out and the files/line numbers comments will be updated.

**Comment by thothix** [comment]
I think we can keep some of removed messages commented so we can reintroduce it in the future if necessary.

**Comment by martinkg** [comment]
@Thothix
translated de-guayadeque.po.txt is attached
[de-guayadeque.po.txt](https://github.com/user-attachments/files/17994048/de-guayadeque.po.txt)

**Comment by martinkg** [comment]
@thothix
small correction
[de-guayadeque.po.txt](https://github.com/user-attachments/files/18003729/de-guayadeque.po.txt)

**Comment by filochard** [comment]
@martinkg @thothix
I have had a look to the last /po/de/guayadeque.po that Tiago (thothix) updated with your  de-guayadeque.po.txt from https://github.com/thothix/guayadeque/issues/25#issuecomment-2514638070

the small correction from https://github.com/thothix/guayadeque/issues/25#issuecomment-2516345003 seems to bring some problems and should not be applied

Besides this 
I have found some  corrections to apply and some missing translations in the last /po/de/guayadeque.po in the dev branch

I will soon upload here a list of suggestions letting you verify them before modifying a new /po/de/guayadeque.po to pull

**Comment by filochard** [comment]
@martinkg 

Here is what I may suggest to correct little errors and to get a coherence in translation 
for each msgid you have the current msgstr and a maybe ? proposed
(NB I don't speak German : I only looked into the existing translation to pick what may give correct sentences that's a kind of private DeepLearning : o )  )

[de-corrections.txt](https://github.com/user-attachments/files/18007933/de-corrections.txt)

Of course, please, you may correct this list and I will then include the corrections in the existing /po/de/guayadeque.po

**Comment by martinkg** [comment]
@filochard @thothix
filochard thank you for your translation. Apart from a few translations, I was able to adopt most of your suggestions
[de-corrections.txt](https://github.com/user-attachments/files/18009281/de-corrections.txt)

**Comment by filochard** [comment]
@martinkg 
Thnaks for having reviewed my suggestions

A doubt remains for me : 
sometimes  the word "library" is tranlated by "Musiksammlung" (that seems to mean music collection)
sometimes the word "library" is translated by "Bibliothek" (that seems to really mean library)
Once we may even find "view the collection library" that should be translated by "Musiksammlung-Bibliothek ansehen"

In a way to keep coherence, maybe should I translate each time strictly "library" by "Bibliothek" instead of "Musiksammlung"
Since the two words (library and collection) appear in the .pot file there may be a reason....
and use "Musiksammlung" to translate "collection" only when it implicitly means "music collection"
and "Sammlung" to translate "collection" when it is strictly used for meaning collection and not used for "music collection"

**Comment by thothix** [comment]
> @martinkg Thnaks for having reviewed my suggestions
> 
> A doubt remains for me : sometimes the word "library" is tranlated by "Musiksammlung" (that seems to mean music collection) sometimes the word "library" is translated by "Bibliothek" (that seems to really mean library) Once we may even find "view the collection library" that should be translated by "Musiksammlung-Bibliothek ansehen"
> 
> In a way to keep coherence, maybe should I translate each time strictly "library" by "Bibliothek" instead of "Musiksammlung" Since the two words (library and collection) appear in the .pot file there may be a reason.... and use "Musiksammlung" to translate "collection" only when it implicitly means "music collection" and "Sammlung" to translate "collection" when it is strictly used for meaning collection and not used for "music collection"

Hi @filochard 

I was taking a look to this Library versus Collection... I had thought to unify the two terms but I found what is the difference.

Library is the aggregation of music tracks (only music tracks) and
Collection is the aggregation of musics (LIBRARY), files, configurations, etc that compose the collection, for instance: The (collection) library, views, layouts, playlists, etc.

**Comment by martinkg** [comment]
@filochard @Thothix
I agree with both of you here.

**Comment by filochard** [comment]
> > @martinkg Thnaks for having reviewed my suggestions
> > A doubt remains for me : sometimes the word "library" is tranlated by "Musiksammlung" (that seems to mean music collection) sometimes the word "library" is translated by "Bibliothek" (that seems to really mean library) Once we may even find "view the collection library" that should be translated by "Musiksammlung-Bibliothek ansehen"
> > In a way to keep coherence, maybe should I translate each time strictly "library" by "Bibliothek" instead of "Musiksammlung" Since the two words (library and collection) appear in the .pot file there may be a reason.... and use "Musiksammlung" to translate "collection" only when it implicitly means "music collection" and "Sammlung" to translate "collection" when it is strictly used for meaning collection and not used for "music collection"
> 
> Hi @filochard
> 
> I was taking a look to this Library versus Collection... I had thought to unify the two terms but I found what is the difference.
> 
> Library is the aggregation of music tracks (only music tracks) and Collection is the aggregation of musics (LIBRARY), files, configurations, etc that compose the collection, for instance: The (collection) library, views, layouts, playlists, etc.

Thanks for having made this understandable
I'm gonna correct this for the de-guayadeque.po file and request a pull after it's done

**Comment by filochard** [comment]
Out of German Translation topic
Now that some misunderstandings are cleared up ...
I will have now to correct some errors in French Greek Italian and Spanish  :-(
Will do this later...

**Comment by martinkg** [comment]
@filochard
One more little thing, this should be translated like this:

#: ui/player/PlayList.cpp:79
msgid "Move the selected tracks to the bottom"
msgstr "Ausgewählte Tracks an das Ende verschieben"

**Comment by filochard** [comment]
Done

**Comment by filochard** [comment]
I think this issue may be closed
All the corrections have been done
There' a Pull Request for this German translation and for the others (French, Greek, Italian, Spanish)
