### ISSUE TITLE
6.1 breaks the system if autostarts with the system

### ISSUE THREAD

**Issue by Evolve-Git** [thothix/guayadeque#29]
Latest Manjaro on 6.6 kernel.
Title. It autostarts hundreds of instances rendering the system unresponsive.
System journal just lists hundreds of successful launches of quayadeque... until it runs out of resources.

**Comment by thothix** [comment]
Hi!
Can you answer some questions?

How did you configure the autostart?
What desktop environment do you use?
Did you install Guayadeque by the Manjaro repository (AUR)?
Did you have another Guayadeque version before install/update to v0.6.1? 

My Manjaro test system is installed with Cinnamon DE and I wasn't able to reproduce this issue.

**Comment by Evolve-Git** [comment]
Its the system autostart, it launches apps that were open during the shutdown.
I use KDE. Guayadeque is installed from the AUR. 
I used it for several years now until the upgrade from 5.3 to 6.1
I really like the player and would love to keep using it.

**Comment by thothix** [comment]
Ok, it's not exactly the autostart, it's actually the KDE restore session.
I have KDE in a Mageia 9, tested it and the restore works fine.
I installed a Manjaro KDE VM and enabled the session restore and it works fine as well. The only thing is that sometimes it gives a "Guayadeque instance is already running" message, and I click Yes to continue loading and it works fine too.

My Manjaro install started with kernel 6.10. Did you choose to use the kernel 6.6 ? Do you have an uptodated system?

Do you have other applications opened on shutdown or only Guayadeque?

If we are not able to solve this by now you can close it before restart/shutdown or add Guayadeque in the session exception in session configuration (to not save it).

It seems some flaw in the session restore. Can you try to reset it (restart with all applications closed) or after that disable the session restore, reboot and enable it again.

**Comment by Evolve-Git** [comment]
I have my browser and a couple more apps (guayadeque included) autostart that way and never had any issues.
Seems like turning the session restore off and on again fixed the issue, at least for 2 reboots.
Thanks for help!
