### ISSUE TITLE
Lyrics seems broken...

### ISSUE THREAD

**Issue by ben2talk** [thothix/guayadeque#4]
I just built this from AUR - very excited to see Guayadeque back because, amongst other things, I love the option (for failed search) to do one click to open browser, copy lyrics and paste them back - saving to the file.

However, now - even if a track already had lyrics embedded, it seems to be stuck 'searching' for a long time even if lyrics are embedded - it seems to fail to check first.

https://i.imgur.com/XB2dwuE.png

**Comment by thothix** [comment]
Hi!
How are your source and target lyrics configuration (embedded and from file selections) ?

**Comment by filochard** [comment]
> I just built this from AUR - very excited to see Guayadeque back because, amongst other things, I love the option (for failed search) to do one click to open browser, copy lyrics and paste them back - saving to the file.
> 
> However, now - even if a track already had lyrics embedded, it seems to be stuck 'searching' for a long time even if lyrics are embedded - it seems to fail to check first.
> 
> https://i.imgur.com/XB2dwuE.png

you need to mark 2 boxes in lyrics settings
![lyrics setting](https://github.com/user-attachments/assets/e2446769-fa1b-4395-8cd6-2011fdf59515)
and to lift embedded in the first line
so that if lyrics are already embedded guayadeque won't have to search them again

Nota Bene : 
In French "paroles" means lyrics  and "préférences" means settings

**Comment by filochard** [comment]
Hi Tiago
I really think it's not a real issue but a configuration problem of ben2talk
Unfortunately he seems not to have tried the solution proposed

Unless you think the lyrics configuration should have the mark box "embedded" marked in the upper place in Sources by default (if there's nothing embedded in the track file that won't prevent Guayadeque to search elsewhere...)

**Comment by thothix** [comment]
> Hi Tiago I really think it's not a real issue but a configuration problem of ben2talk Unfortunately he seems not to have tried the solution proposed
> 
> Unless you think the lyrics configuration should have the mark box "embedded" marked in the upper place in Sources by default (if there's nothing embedded in the track file that won't prevent Guayadeque to search elsewhere...)

Yes, I don't know if he changed his config and solved his issue. As he didn't reply I'm closing the issue.

**Comment by thothix** [comment]
> Unless you think the lyrics configuration should have the mark box "embedded" marked in the upper place in Sources by default (if there's nothing embedded in the track file that won't prevent Guayadeque to search elsewhere...)

I think it's a good idea. I'm going to change this in the next release. I didn't expect to release 0.6.1 earlier this week.

**Comment by filochard** [comment]
Hi Tiago
About lyrics setting the default is this one : 
![settings1](https://github.com/user-attachments/assets/0bb813ff-ada6-4821-a528-5ba9a6c3556c)
I think this would be this by default : 
![settings2](https://github.com/user-attachments/assets/af170454-afd2-4f25-a0b9-ae2725842649)
In this case if there's no lyrics embedded the search runs, but if lyrics are already embedded no search is done and the lyrics can immediately be displayed

I think too that the better place to store lyrics is to embed them in the track file (this file can be used by an other music player and contents the lyrics that can be displayed if this other music player allows this)
