### ISSUE TITLE
0.6.0 release (renamed from 0.5.4)

### ISSUE THREAD

**Issue by thothix** [thothix/guayadeque#6]
I don't have anything yet to the next release but opened this to be able to communicate any news.

**Comment by thothix** [comment]
https://github.com/anonbeat/guayadeque/issues/104

I already do search like that (search without accent for musics/artists with accents) and it works properly.

@filochard Do you have this issue?

**Comment by filochard** [comment]
Hi Tiago
Indeed lots of French names or words contains accents...
Tagging each track I have usually used accents for French titles
Until now when searching this kind of music I always used accents and never noticed that if not accented the search gives nothing.

I can confirm now that the problem exists, for example  : 
looking fo chérie gives : 
- an album "Ecoute ça **chérie**" from the group "Bratsch"
- a title "Mon amour ma **chérie**" from "Amadou & Mariam"
- a title "Ma petite **chérie**" from the group "Debout sur le Zinc"

looking for cherie gives : 
- a title "por**cherie**" from the artist "les Béruriers Noirs"
- an artist name "Mark de Clive lowe featuring **Cherie** Mathieson"

I  am not sure that this should be corrected : looking in the mean time for accented and not accented words would give a huge result partially irrelevant for French users (we use a à â e é è ê ë i î  ï o ô u ù)

Nevertheless the reason stays here : 
you forked from openmonk before his commit from november 24 2023 : 8636427 "collate accents on media search" that solved this issue in anonbeat repo
https://github.com/openmonk/guayadeque/commits/collate-search/

Nota Bene : 
this commit from openmonk needs an extra BuildRequires : icu
it needs to increase too the search timer

**Comment by thothix** [comment]
Ok, I did only a quick test and it was wrong! Anyway I already have the openmonk commits merged in my branch.
I'll test it and it'll be in the next release.

**Comment by filochard** [comment]
> Ok, I did only a quick test and it was wrong! Anyway I already have the openmonk commits merged in my branch. I'll test it and it'll be in the next release.

I'm not sure if this will be an improvement : such a query will bring lots of useless tracks if you explicitly use a query without accent and not for tracks with an accent 
Nevertheless openmonk found an answer for this issue (even if anonbeat had let it opened)

**Comment by thothix** [comment]
How we say

**Comment by thothix** [comment]
How do you say "Show album cover in the player" in french ?

**Comment by filochard** [comment]
> How do you say "Show album cover in the player" in french ?

We may say
"Afficher la pochette de l'album dans le lecteur"  
or 
"Afficher la jaquette de l'album dans le lecteur"

Indeed in the French .po file  of Guayadeque "cover" is already translated as "pochette"

So the first translation is the best in this context :-)

**Comment by filochard** [comment]
I may add some translations for 4 of the pictures now present in the top of the playlist : 

- "move the selected tracks to the top"         "déplacer les morceaux sélectionnés en début de liste"
- "move the selected tracks up"                      "déplacer les morceaux sélectionnés d'un rang vers le haut "
- "move the selected tracks down"                 "déplacer les morceaux sélectionnés d'un rang vers le bas"
- "move the selected tracks to the bottom"   "déplacer les morceaux sélectionnés en fin de liste"

**Comment by filochard** [comment]
Hi Tiago
I've just seen the huge work you have done on 0.5.4-beta ....  As soon as you think it's ready for test I'll try it
( I can test it already with your commit 3622702 if you want...)

I have only something to notice about INSTALL.md : 
- under BUILD 
you may add libicu in the list of needed installed packages
- for Mageia9 (it may be useless since we provide a built package) the BuildRequires are these ones : 

desktop-file-utils ,  imagemagick, libmp4v2-devel, wxgtk-devel,  pkgconfig(libcurl), pkgconfig(dbus-1), pkgconfig(flac), pkgconfig(icu-i18n), pkgconfig(libgpod-1.0), pkgconfig(gstreamer-1.0), pkgconfig(jsoncpp),  pkgconfig(sqlite3), pkgconfig(taglib), pkgconfig(wxsqlite3),  pkgconfig(libxml-2.0)

**Comment by filochard** [comment]
Hi
I have tested 0.5.4-beta from commit 3622702

It works now for searching without accent : cherie gives now : 
- a title "porcherie" from the artist "les Béruriers Noirs"
- an artist name "Mark de Clive lowe featuring Cherie Mathieson
and
- an album "Ecoute ça chérie" from the group "Bratsch"
- a title "Mon amour ma chérie" from "Amadou & Mariam"
- a title "Ma petite chérie" from the group "Debout sur le Zinc"

translations for playlist icons are right in French

in  preferences 
the checkbox  for displaying the cover in the player works when marked or not marked ("show album cover in the player")
When we click on the album cover in the player this increases temporarily the size of the picture...

nevertheless the second checkbox ("show CD cover frame in the player") is not really necessary : 
When we click on the album cover in the player this increases temporarily the size of the picture but inside a CD frame so the picture is a little less great than when only the first checkbox is marked...

If you keep it,  the translation should be "afficher la pochette comme un boîtier de CD dans le lecteur"


Nice job
And skilled comprehension of the source
Congratulations

**Comment by thothix** [comment]
Thanks for testing @filochard !

I found the search with collation a bit slow.

I agree that "show CD cover frame in the player" configuration is a bit useless.

**Comment by filochard** [comment]
The search with collation is not slow for me (even with 18 000 tracks in the database)

But I regret not being able to look for something strictly  written with an accent 
Looking for "chérie" (with a é) in the search bar  I get in fact everything containing chérie but cherie too (like in https://github.com/thothix/guayadeque/issues/6#issuecomment-2396975384)

Worse result :  looking for "**Éric**"  ( I didn't remember the full name of this French jazzman which is Éric Schaefer and intend to find it this way)
Guayadeque 5.3.0 found 25 items containing  "Éric"  : 15 times Éric Schaefer as an artist 

 With 5.4.0-beta , looking for **Éric** I get now 627 other items with eric  **eric** Clapton, Am**eric**an life, Panam**eric**a , Am**eric**an folk music, Fred**eric** Loewe, J**eric**ho, and so on

This is not very friendly for a French user : we use lots of accents and sometimes it is the only difference
 between a French name or word and names and words in other language  
or even between 2 French words : né (=born) ne (=not)

Indeed for a French user it may not be so useful with correctly tagged files (with all the needed accents) ...

But I understand that for other users the French tags may be not found : that was the example in anonbeat issue 
("la Boheme " didn't allow to find "la Bohème")

**Comment by thothix** [comment]
> The search with collation is not slow for me (even with 18 000 tracks in the database)
> 
I have 59000 in my main collection, the search in the end is ok but it freezes a bit when I'm typing the query.

> But I regret not being able to look for something strictly written with an accent Looking for "chérie" (with a é) in the search bar I get in fact everything containing chérie but cherie too (like in [#6 (comment)](https://github.com/thothix/guayadeque/issues/6#issuecomment-2396975384))
>
> Worse result : looking for "**Éric**" ( I didn't remember the full name of this French jazzman which is Éric Schaefer and intend to find it this way) Guayadeque 5.3.0 found 25 items containing "Éric" : 15 times Éric Schaefer as an artist
> 
> With 5.4.0-beta , looking for **Éric** I get now 627 other items with eric **eric** Clapton, Am**eric**an life, Panam**eric**a , Am**eric**an folk music, Fred**eric** Loewe, J**eric**ho, and so on
> 
> This is not very friendly for a French user : we use lots of accents and sometimes it is the only difference between a French name or word and names and words in other language or even between 2 French words : né (=born) ne (=not)
>
I understand, we have some cases like that in portuguese.
 
> Indeed for a French user it may not be so useful with correctly tagged files (with all the needed accents) ...
> 
This is a good question, to maintain the files correctly tagged! I try to maintain them up to date but it's a lot of work. I have another collection with thousands of musics that aren't fully tagged.
> But I understand that for other users the French tags may be not found : that was the example in anonbeat issue ("la Boheme " didn't allow to find "la Bohème")

I am going to research a bit to see if we can treat the search with accents in a different way and maybe we can put some configuration for this in Preferences

**Comment by thothix** [comment]
Development branch now is the permanent "dev" branch, it's not "version-beta" (0.5.x-beta) anymore.

**Comment by thothix** [comment]
I have renamed the next release from 0.5.4 to 0.6.0 cause I made a couple of bigger aditions (New Library Directory Panel and Collate search)

**Comment by filochard** [comment]
Hi Tiago
I am having a look inside the dev branch (I'm gonna test it soon)

in guayadeque/po/fr/guayadeque.po  there is a little correction to apply
line 3226
msgstr "Afficher la fenêtre de la pochette dans le Éditeur de pochettes"
might be
msgstr "Afficher la fenêtre de la pochette dans l'éditeur de pochettes"

**Comment by thothix** [comment]
Translation updated, thanks.
I'm testing and fixing some bugs that I already found.

**Comment by thothix** [comment]
Committed right now some fixes (3d7a0605fd25cbc65e0e361da6e5ba18b6d441ee)

**Comment by filochard** [comment]
I have just tested guayadeque 0.6.0 beta4 release (commit 4f562da)
- 1)  It works perfectly as a fresh install 
(having backed up the /home/myusername/.guayadeque as /home/myusername/.guayadequebak) : 
it creates a new /home/myusername/.guayadeque that I can configure as I want
- 2) it works perfectly as an update
(I use a copy of /home/myusername/.guayadequebak named /home/myusername/.guayadeque)
everything is OK

There's only one thing that works strangely : 
when I refresh the database of radios and look for local radios I find all of them except that I can't find anymore the radios from Radio France : 
- France Inter
- France Musique
- France Culture
- France Info
- Radio Bleue Drôme Isère

None of these Radio France stations (we may add FIP) can be found anywhere in the list of French national radios

I know that their addresses have been modified and that they can now be found on 
http://icecast.radiofrance.fr/ 
such as
http://icecast.radiofrance.fr/franceinter-hifi.aac as an example

If you look on the following address inside letter F you may find all the addresses of the French national radios : 
http://fluxradios.blogspot.com/p/flux-radios-francaise.html#Radios%20Nationales
you may find FIP too (France Inter Paris) that is not a local radio

I don't know what is the web source from where guayadeque refreshes its list of radios but it seems to have not been updated to provide the recent new URLs

**Comment by filochard** [comment]
Post Scriptum
I have been able to add in "my radios" the radios from Radio France one by one with the icecast address of each one
This works with a quite hifi sound (aac 192 !)

**Comment by filochard** [comment]
I have found the reason why some local or national radios of France can't be found : 
Guayadeque seems to download its database from the database of Tunein
But all the radio stations of Radio France (France Inter, France Musique, France Culture, France Info, F.I.P, France Bleue) are no more in the database of Tunein ...
 there seems to be some conditions to be referenced by tunein that are not admissible for national radios such as 
- allowing tunein to add advertising when it's used to listen to them 
- allowing tunein to infringe the copyrights, music rights...

Radio France has not found an agreement with Tunein and since april 2024 all its stations are no more referenced (this is explained here, in French...
https://mediateur.radiofrance.com/actualites/lecoute-de-radio-france-via-tunein/

There's nothing to do inside Guayadeque source to correct this problem : an user has to manually add these Radio Stations if he wants to hear them through Guayadeque

**Comment by filochard** [comment]
Hi 
I have tested 0.6.0 beta6
everything seems OK (fresh install or using a previously created  /home/myusername/.guayadeque )
I can record a radio (in format mp3 even if the original is in aac)

**Comment by thothix** [comment]
> I have found the reason why some local or national radios of France can't be found : Guayadeque seems to download its database from the database of Tunein But all the radio stations of Radio France (France Inter, France Musique, France Culture, France Info, F.I.P, France Bleue) are no more in the database of Tunein ... there seems to be some conditions to be referenced by tunein that are not admissible for national radios such as
> 
>     * allowing tunein to add advertising when it's used to listen to them
> 
>     * allowing tunein to infringe the copyrights, music rights...
> 
> 
> Radio France has not found an agreement with Tunein and since april 2024 all its stations are no more referenced (this is explained here, in French... https://mediateur.radiofrance.com/actualites/lecoute-de-radio-france-via-tunein/
> 
> There's nothing to do inside Guayadeque source to correct this problem : an user has to manually add these Radio Stations if he wants to hear them through Guayadeque

I'm going to put this information in the next release README, ok?

**Comment by thothix** [comment]
v0.6.0 released.

I'm not going to implement new features soon. So I'll be working in some research and enhancements based on reports I received like enhanced collate search and investigating audio recording issues

**Comment by filochard** [comment]
built and tested guayadeque 0.6.0 
It's perfect (as fresh install or as an update of previous version)

I have the list of the RadioFrance stations provided by icecast :   I don't how to create something to add them optionally  to the radio.db or if this can be added in the README 

France Musique
- France Musique https://icecast.radiofrance.fr/francemusique-hifi.aac?id=radiofrance
- France Musique baroque https://icecast.radiofrance.fr/francemusiquebaroque-hifi.aac?id=radiofrance
- France Musique classique plus https://icecast.radiofrance.fr/francemusiqueclassiqueplus-hifi.aac?id=radiofrance
- France Musique concert Radio France https://icecast.radiofrance.fr/francemusiqueconcertsradiofrance-hifi.aac?id=radiofrance
- France Musique easy classique https://icecast.radiofrance.fr/francemusiqueeasyclassique-hifi.aac?id=radiofrance
- France Musique labo https://icecast.radiofrance.fr/francemusiquelabo-hifi.aac?id=radiofrance
- France Musique contemporaine https://icecast.radiofrance.fr/francemusiquelacontemporaine-hifi.aac?id=radiofrance
- France Musique jazz https://icecast.radiofrance.fr/francemusiquelajazz-hifi.aac?id=radiofrance
- France Musique Ocora musiques du monde https://icecast.radiofrance.fr/francemusiqueocoramonde-hifi.aac?id=radiofrance

FIP (France Inter Paris)
- FIP     https://icecast.radiofrance.fr/fip-hifi.aac?id=radiofrance
- FIP electro    https://icecast.radiofrance.fr/fipelectro-hifi.aac?id=radiofrance
- FIP groove https://icecast.radiofrance.fr/fipgroove-hifi.aac?id=radiofrance
- FIP hiphop https://icecast.radiofrance.fr/fiphiphop-hifi.aac?id=radiofrance
- FIP jazz https://icecast.radiofrance.fr/fipjazz-hifi.aac?id=radiofrance
- FIP metal https://icecast.radiofrance.fr/fipmetal-hifi.aac?id=radiofrance
- FIP nouveautés https://icecast.radiofrance.fr/fipnouveautes-hifi.aac?id=radiofrance
- FIP pop https://icecast.radiofrance.fr/fippop-hifi.aac?id=radiofrance
- FIP reggae https://icecast.radiofrance.fr/fipreggae-hifi.aac?id=radiofrance
- FIP rock https://icecast.radiofrance.fr/fiprock-hifi.aac?id=radiofrance
- FIP sacré français https://icecast.radiofrance.fr/fipsacrefrancais-hifi.aac?id=radiofrance
- FIP world https://icecast.radiofrance.fr/fipworld-hifi.aac?id=radiofrance

France Culture  https://icecast.radiofrance.fr/franceculture-hifi.aac?id=radiofrance

France Inter  https://icecast.radiofrance.fr/franceinter-hifi.aac?id=radiofrance

France Info  http://icecast.radiofrance.fr/franceinfo-hifi.aac

**Comment by thothix** [comment]
Maybe I can add it to a new "RADIOS.md" file to not bloat the README...

**Comment by filochard** [comment]
> Maybe I can add it to a new "RADIOS.md" file to not bloat the README...

This seems to be a good way to inform users who want to manually add those stations (we can't modify the refreshed  db downloaded from TuneIn)
