### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by thothix** [thothix/guayadeque#7]
I had created this issue to post the updates for the version 0.5.1 and to receive feedback and suggestions about it.

The priority for this release is bug fixes and compatibility updates but there's room for small enhancements as well.

For bugs  or requests please check the issues and open one if needed.

**Comment by thothix** [comment]
- Write the partial scanning in the library to speed up following rescans

- Fixed compatibility with Gstreamer below 1.20

**Comment by filochard** [comment]
Hi Tiago
 I'm testing 0.5.1 version
it seems OK

I get only this warning when building (that doesn't prevent to build nor to work)
I had not noticed that before but it was certainly present

/builddir/build/BUILD/guayadeque-0.5.1/src/misc/MD5.cpp:183:21: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  183 |     register uint32 a, b, c, d;
      |                     ^
/builddir/build/BUILD/guayadeque-0.5.1/src/misc/MD5.cpp:183:24: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  183 |     register uint32 a, b, c, d;
      |                        ^
/builddir/build/BUILD/guayadeque-0.5.1/src/misc/MD5.cpp:183:27: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  183 |     register uint32 a, b, c, d;
      |                           ^
/builddir/build/BUILD/guayadeque-0.5.1/src/misc/MD5.cpp:183:30: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  183 |     register uint32 a, b, c, d;
      |                              ^

**Comment by thothix** [comment]
I had updated the 0.5.1 right now but I'm not getting this warnings even in Mageia

**Comment by filochard** [comment]
I built 0.5.1 just before your last commit
This warning appears during step 33/161 of the build
both on Mageia9 and Cauldron
But that doesn't prevent to build and to work :-)

The MD5.cpp is here since year 2016 ....

**Comment by thothix** [comment]
Ok, but I don't understand because I have Mageia 9 uptodated and I don't get this warnings. Maybe in Caldron the new g++ is a C++17 version by default

**Comment by raschaa** [comment]
Just built  0.5.1 on Mint 21.3
No errors on build
It did crash Cinnamon while I was trying to reconstruct my personal layout.... will give that another look later

**Comment by filochard** [comment]
Don't worry about this ...

Out of this topic

I have a little problem with the releases tags since they don't refer always to the same commit step : 
 you have updated the source but the release has always the same number : 
 I have built 0.5.0 for Mageia when it appeared, and I used a link to the commit named 
"Guayadeque 0.5.0 annoncement"(67825ee)

but the latest 0.5.0 release source is not exactly the same if I download it again... it leads to the commit "0.5.0 release update" (4d85ad4)
It's problematic since I already provided an update for Mageia9 with the initial version of the source

I will wait until 0.5.1 is stabilized before providing it

**Comment by thothix** [comment]
Yes, I did some adjustments in 0.5.0 and reissued the release. Maybe I should release a 0.5.0.1 instead.

The release 0.5.1 is finished, I'll not update it again. I no code to commit right now so if I need I'll issue a 0.5.2 or 0.5.1.1

**Comment by thothix** [comment]
> Just built 0.5.1 on Mint 21.3 No errors on build It did crash Cinnamon while I was trying to reconstruct my personal layout.... will give that another look later

The 0.5.0 build in Mint 20 breaks, the more recent Mint versions build fine

**Comment by thothix** [comment]
Don't release 0.5.1, it's broken

**Comment by filochard** [comment]
> > Just built 0.5.1 on Mint 21.3 No errors on build It did crash Cinnamon while I was trying to reconstruct my personal layout.... will give that another look later
> 
> The 0.5.0 build in Mint 20 breaks, the more recent Mint versions build fine The 0.5.1 build fine in all Mint versions

that's certainly because of the gstreamer version inside Mint20 the reason why 0.5.0 build in Mint 20 breaks
your commit about compatibility (4881251) solved the problem  nice catch !

**Comment by thothix** [comment]
All accelerator key was messed up! 

Fixed and updated the release

**Comment by thothix** [comment]
Release updated again!

**Comment by filochard** [comment]
I don't use neither Debian nor Ubuntu, and don't know anything about their packagers
Nevertheless I have mailed to the Fedora packager of Guayadeque to inform him about your fork which needs advertising

**Comment by filochard** [comment]
I have mailed to the opensuse maintainer too (rpm based like Fedora and Mageia)

**Comment by thothix** [comment]
Ok, thank you

**Comment by thothix** [comment]
I sent a message to anonbeat a week ago but he didn't answer until now. 
I'll keep waiting and working on Guayadeque and if needed I'll do a real fork without forking his repository but I wouldn't like to change Guayadeque's name.

**Comment by thothix** [comment]
I'm going to reload my Guayadeque repository without the openmonk fork so github will not ask me to do pull requests to upstream anymore. The releases will be maintained, I'm going to lose only the past issues.

I'm closing this issue as well.
